Tienda1/src/java/control/CarroCompraController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package control;


import static com.sun.faces.el.FacesCompositeELResolver.ELResolverChainType.Faces;
import entidad.Cliente;
import entidad.Libro;
import entidad.Pedido;
import java.io.IOException;
import java.io.Serializable;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import org.primefaces.context.RequestContext;
import org.primefaces.event.DragDropEvent;

/**
 *
 * @author shadow
 */
@ManagedBean(name="carroCompra")
@SessionScoped
public class CarroCompraController implements Serializable{
    private Libro libro;
    private List<Libro> carro;
    private Itemcar itemcar;
    private List<Itemcar> carrocompra;
    private int cant=0;
    private int cantidad=0;
    private BigDecimal subtotal=new BigDecimal(0);
    private BigDecimal subt=new BigDecimal(0);
    private BigDecimal total=new BigDecimal(0);
    private BigDecimal dep=new BigDecimal(0);
    private Pedido pedido;
    private Cliente cliente=new Cliente();
    @ManagedProperty(value="#{clienteBean}")
    private ClienteController clienteBean;
    @ManagedProperty(value="#{PedidoBean}")
    private PedidoController pedidoBean;
    @EJB
    private stateless.ClienteFacade clienteFacade;
    @EJB
    private stateless.PedidoFacade pedidoFacade;
    private Date fechapedido;
    private int numaut=0;
    private int nump=0;
    @PostConstruct
    public void init(){
        carrocompra=new ArrayList<Itemcar>();
        carro=new ArrayList<Libro>();
    }
    
    /**
     * Creates a new instance of CarroCompra
     */
    public CarroCompraController() {
    }
    
    public void addPedido(){
        numaut++;
        clienteFacade.save(cliente);
        fechapedido=new Date();
        pedido=new Pedido();
        pedido.setConfirmacionApartado(numaut);
        pedido.setDeposito(dep);
        pedido.setFecha(fechapedido);
        pedido.setIdCliente(cliente);
        pedido.setStatus(0);
        pedido.setSubtotal(total);
        pedidoFacade.save(pedido);
        nump=pedido.getNumeroPedido();
        try {
            FacesContext.getCurrentInstance().getExternalContext().redirect("Ticket.xhtml");
        } catch (IOException ex) {
            Logger.getLogger(CarroCompraController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void sesionClear(){
        try {
            FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
            FacesContext.getCurrentInstance().getExternalContext().redirect("../index.xhtml");
        } catch (IOException ex) {
            Logger.getLogger(CarroCompraController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void addCarro(Libro lib){
        libro=lib;
        if(carrocompra.isEmpty()){
            itemcar=new Itemcar();
            itemcar.setLibro(lib);
            cant++;
            subtotal=libro.getPrecio();
            itemcar.setCantidad(1);
            itemcar.setTotal(subtotal);
            carrocompra.add(itemcar);
            calcCantidadTotal();
            calcSubtotal();;
            System.out.println("primer if");
            //calcSubtotal();
        }else{
            boolean libexist=false;
            int x=0;
            System.out.println("elsef");
            for(int i=0;i<carrocompra.size();i++){
                if(carrocompra.get(i).getLibro().getIsbn().compareTo(libro.getIsbn())==0){
                    libexist=true;
                    x=i;
                    System.out.println("for");
                    //cantidad++;
                }else{
                    libexist=false;
                    System.out.println("else dentro de else");
                }
            }
            if(libexist){
                carrocompra.get(x).setCantidad(carrocompra.get(x).getCantidad()+1);
                System.out.println("");
                calcCantidadTotal();
                calcSubtotal();
            }else{
                itemcar=new Itemcar();
                itemcar.setLibro(lib);
                itemcar.setCantidad(1);
                itemcar.setTotal(libro.getPrecio());
                carrocompra.add(itemcar);
                calcCantidadTotal();
                calcSubtotal();
            }
        }
       
    }
    public void agregarCarro(Libro lib){
        System.out.println("size "+carro.size());
        //System.out.println("libro "+libro);
        libro=lib;
        if(carro.isEmpty()){
            System.out.println("empty");
            carro.add(libro);
            total=libro.getPrecio();
            cantidad++;
        }else{
            System.out.println("libro "+libro);
            boolean libexist=false;
            int x=0;
            for(int i=0;i<carro.size();i++){
                if(carro.get(i).getIsbn().compareTo(libro.getIsbn())==0){
                    libexist=true;
                    x=i;
                }else{
                    libexist=false;
                }
            }
            if(libexist){
                cantidad++;
                
                BigDecimal t= total.add(libro.getPrecio());
                total=t;
            }else{
                carro.add(libro);
            }
            //cantidad++;
            //BigDecimal t= total.add(libro.getPrecio());
            //total=t;
            //carro.add(libro);
        }
    }
    
    public void removeCarro(Libro lib){
        libro=lib;
        System.out.println(""+lib.getIsbn());
        for (int i = 0; i < carrocompra.size(); i++) {
            if(carrocompra.get(i).getLibro().getIsbn().compareTo(libro.getIsbn())==0){
                if(carrocompra.get(i).getCantidad()>1){
                    carrocompra.get(i).setCantidad(carrocompra.get(i).getCantidad()-1);
                    calcSubtotal();
                    calcCantidadTotal();
                }else{
                    carrocompra.remove(i);
                    calcSubtotal();
                    calcCantidadTotal();
                }
            }
        }
         
    }
    
    public void calcSubtotal(){
        total=new BigDecimal(0);
        for (int i = 0; i < carrocompra.size(); i++) {
            total=total.add(carrocompra.get(i).getLibro().getPrecio().multiply(new BigDecimal(carrocompra.get(i).getCantidad())));
        }
        
    }
    public void calcCantidadTotal(){
        cantidad=0;
        for (int i = 0; i < carrocompra.size(); i++) {
            cantidad+=carrocompra.get(i).getCantidad();
        }
    }
    
    public void calculaDeposito(){
        BigDecimal porcent=new BigDecimal(0.20);
        dep=total.multiply(porcent);
        dep = dep.setScale(2, RoundingMode.CEILING);
    }
    
    public void pagar(){
        calculaDeposito();
        if(carrocompra.isEmpty()){
            try {
                FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Info" ,"Tu carro de compra esta vacio ") );
                FacesContext.getCurrentInstance().getExternalContext().redirect("index.xhtml");
            } catch (IOException ex) {
                Logger.getLogger(CarroCompraController.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try {
                FacesContext.getCurrentInstance().getExternalContext().redirect("cliente/login.xhtml");
                //FacesContext.getCurrentInstance().getExternalContext().redirect("libro/RegistroCliente.xhtml");
            } catch (IOException ex) {
                Logger.getLogger(CarroCompraController.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }
    
    public void onLibroDrop(DragDropEvent ddEvent) {
        Libro lib = ((Libro) ddEvent.getData());
        addCarro(lib);
    }
    
    public void regresar(){
        try {
            FacesContext.getCurrentInstance().getExternalContext().redirect("../index.xhtml");
        } catch (IOException ex) {
            Logger.getLogger(CarroCompraController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void cleanCarro(){
        carrocompra.clear();
        calcSubtotal();
        calcCantidadTotal();
        System.out.println(""+carrocompra.size());
    }
    /**
     * @return the libro
     */
    public Libro getLibro() {
        return libro;
    }

    /**
     * @param libro the libro to set
     */
    public void setLibro(Libro libro) {
        this.libro = libro;
    }

    /**
     * @return the carro
     */
    public List<Libro> getCarro() {
        return carro;
    }

    /**
     * @param carro the carro to set
     */
    public void setCarro(List<Libro> carro) {
        this.carro = carro;
    }

    /**
     * @return the cantidad
     */
    public int getCantidad() {
        return cantidad;
    }

    /**
     * @param cantidad the cantidad to set
     */
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    /**
     * @return the total
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * @param total the total to set
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * @return the cant
     */
    public int getCant() {
        return cant;
    }

    /**
     * @param cant the cant to set
     */
    public void setCant(int cant) {
        this.cant = cant;
    }

    /**
     * @return the itemcar
     */

Tienda1/src/java/control/LibroController.java
package control;

import entidad.Libro;
import control.util.JsfUtil;
import control.util.PaginationHelper;
import stateless.LibroFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("libroController")
@SessionScoped
public class LibroController implements Serializable {

    private Libro current;
    private DataModel items = null;
    @EJB
    private stateless.LibroFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public LibroController() {
    }

    public Libro getSelected() {
        if (current == null) {
            current = new Libro();
            selectedItemIndex = -1;
        }
        return current;
    }

    private LibroFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Libro) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Libro();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("LibroCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Libro) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("LibroUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Libro) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("LibroDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Libro getLibro(java.lang.String id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Libro.class)
    public static class LibroControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            LibroController controller = (LibroController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "libroController");
            return controller.getLibro(getKey(value));
        }

        java.lang.String getKey(String value) {
            java.lang.String key;
            key = value;
            return key;
        }

        String getStringKey(java.lang.String value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Libro) {
                Libro o = (Libro) object;
                return getStringKey(o.getIsbn());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Libro.class.getName());
            }
        }

    }

}

Tienda1/web/libro/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateLibroTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateLibroLabel_isbn}" for="isbn" />
                    <h:inputText id="isbn" value="#{libroController.selected.isbn}" title="#{bundle.CreateLibroTitle_isbn}" required="true" requiredMessage="#{bundle.CreateLibroRequiredMessage_isbn}"/>
                    <h:outputLabel value="#{bundle.CreateLibroLabel_titulo}" for="titulo" />
                    <h:inputText id="titulo" value="#{libroController.selected.titulo}" title="#{bundle.CreateLibroTitle_titulo}" required="true" requiredMessage="#{bundle.CreateLibroRequiredMessage_titulo}"/>
                    <h:outputLabel value="#{bundle.CreateLibroLabel_existencias}" for="existencias" />
                    <h:inputText id="existencias" value="#{libroController.selected.existencias}" title="#{bundle.CreateLibroTitle_existencias}" required="true" requiredMessage="#{bundle.CreateLibroRequiredMessage_existencias}"/>
                    <h:outputLabel value="#{bundle.CreateLibroLabel_precio}" for="precio" />
                    <h:inputText id="precio" value="#{libroController.selected.precio}" title="#{bundle.CreateLibroTitle_precio}" required="true" requiredMessage="#{bundle.CreateLibroRequiredMessage_precio}"/>
                    <h:outputLabel value="#{bundle.CreateLibroLabel_descripcion}" for="descripcion" />
                    <h:inputText id="descripcion" value="#{libroController.selected.descripcion}" title="#{bundle.CreateLibroTitle_descripcion}" required="true" requiredMessage="#{bundle.CreateLibroRequiredMessage_descripcion}"/>
                    <h:outputLabel value="#{bundle.CreateLibroLabel_idCategoria}" for="idCategoria" />
                    <h:selectOneMenu id="idCategoria" value="#{libroController.selected.idCategoria}" title="#{bundle.CreateLibroTitle_idCategoria}" required="true" requiredMessage="#{bundle.CreateLibroRequiredMessage_idCategoria}">
                        <f:selectItems value="#{categoriaController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{libroController.create}" value="#{bundle.CreateLibroSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{libroController.prepareList}" value="#{bundle.CreateLibroShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateLibroIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

Tienda1/web/libro/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditLibroTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditLibroLabel_isbn}" for="isbn" />
                    <h:inputText id="isbn" value="#{libroController.selected.isbn}" title="#{bundle.EditLibroTitle_isbn}" required="true" requiredMessage="#{bundle.EditLibroRequiredMessage_isbn}"/>
                    <h:outputLabel value="#{bundle.EditLibroLabel_titulo}" for="titulo" />
                    <h:inputText id="titulo" value="#{libroController.selected.titulo}" title="#{bundle.EditLibroTitle_titulo}" required="true" requiredMessage="#{bundle.EditLibroRequiredMessage_titulo}"/>
                    <h:outputLabel value="#{bundle.EditLibroLabel_existencias}" for="existencias" />
                    <h:inputText id="existencias" value="#{libroController.selected.existencias}" title="#{bundle.EditLibroTitle_existencias}" required="true" requiredMessage="#{bundle.EditLibroRequiredMessage_existencias}"/>
                    <h:outputLabel value="#{bundle.EditLibroLabel_precio}" for="precio" />
                    <h:inputText id="precio" value="#{libroController.selected.precio}" title="#{bundle.EditLibroTitle_precio}" required="true" requiredMessage="#{bundle.EditLibroRequiredMessage_precio}"/>
                    <h:outputLabel value="#{bundle.EditLibroLabel_descripcion}" for="descripcion" />
                    <h:inputText id="descripcion" value="#{libroController.selected.descripcion}" title="#{bundle.EditLibroTitle_descripcion}" required="true" requiredMessage="#{bundle.EditLibroRequiredMessage_descripcion}"/>
                    <h:outputLabel value="#{bundle.EditLibroLabel_idCategoria}" for="idCategoria" />
                    <h:selectOneMenu id="idCategoria" value="#{libroController.selected.idCategoria}" title="#{bundle.EditLibroTitle_idCategoria}" required="true" requiredMessage="#{bundle.EditLibroRequiredMessage_idCategoria}">
                        <f:selectItems value="#{categoriaController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{libroController.update}" value="#{bundle.EditLibroSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditLibroViewLink}"/>
                <br />
                <h:commandLink action="#{libroController.prepareList}" value="#{bundle.EditLibroShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditLibroIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

Tienda1/web/libro/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListLibroTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListLibroEmpty}" rendered="#{libroController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{libroController.items.rowCount > 0}">
                    <h:outputText value="#{libroController.pagination.pageFirstItem + 1}..#{libroController.pagination.pageLastItem + 1}/#{libroController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{libroController.previous}" value="#{bundle.Previous} #{libroController.pagination.pageSize}" rendered="#{libroController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{libroController.next}" value="#{bundle.Next} #{libroController.pagination.pageSize}" rendered="#{libroController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{libroController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLibroTitle_isbn}"/>
                            </f:facet>
                            <h:outputText value="#{item.isbn}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLibroTitle_titulo}"/>
                            </f:facet>
                            <h:outputText value="#{item.titulo}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLibroTitle_existencias}"/>
                            </f:facet>
                            <h:outputText value="#{item.existencias}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLibroTitle_precio}"/>
                            </f:facet>
                            <h:outputText value="#{item.precio}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLibroTitle_descripcion}"/>
                            </f:facet>
                            <h:outputText value="#{item.descripcion}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLibroTitle_idCategoria}"/>
                            </f:facet>
                            <h:outputText value="#{item.idCategoria}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{libroController.prepareView}" value="#{bundle.ListLibroViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{libroController.prepareEdit}" value="#{bundle.ListLibroEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{libroController.destroy}" value="#{bundle.ListLibroDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{libroController.prepareCreate}" value="#{bundle.ListLibroCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListLibroIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

Tienda1/web/libro/Ticket.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h:form>
        <h:panelGrid columns="2">
            <h:outputText value="Número de autorización: " />
            <h:outputText value="#{carroCompra.numaut}" />
            <h:outputText value="Número de pedido: " />
            <h:outputText value="#{carroCompra.nump}" />
            <h:outputText value="Porfavor imprima o guarde este numero" />
            <h:commandButton value="Regresar a inicio" action="#{carroCompra.sesionClear()}" ></h:commandButton>
        </h:panelGrid>
        </h:form>
    </h:body>
</html>